[package]
name = "hyper-util-dns-with-span"
version = "0.1.0"
edition = "2024"

[dependencies]
demo = { path = "../demo" }
reqwest = { version = "0.12.15" }

[patch.crates-io]
hyper-util = { git = "https://github.com/hyperium/hyper-util.git", rev = "e7b396628006f5c9279b4f93a6a3ca8a94a2548d" }