[package]
name = "hyper-util-dns-without-span"
version = "0.1.0"
edition = "2024"

[dependencies]
demo = { path = "../demo" }
reqwest = { version = "0.12.15" }

[patch.crates-io]
hyper-util = { git = "https://github.com/arpadav/hyper-util/", branch = "legacyclient-tracing-span-removed" }